import { useEffect, useRef, useState } from 'react';
import WordCloud from './WordCloud';
import { api, write, errorText, setCsrf, ApiError, type Question, type Stats, type Answer, type Word } from './api';
const time = (value: string | null) => value ? new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '暂无回答';
export default function AdminPage() {
  const [auth, setAuth] = useState<'loading' | 'login' | 'ready'>('loading');
  const [username, setUsername] = useState('admin'), [password, setPassword] = useState('');
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [questions, setQuestions] = useState<Question[]>([]), [qid, setQid] = useState<number | null>(null), [stats, setStats] = useState<Stats | null>(null);
  const [tab, setTab] = useState('cloud'), [full, setFull] = useState(false), [lastSync, setLastSync] = useState('');
  const [answers, setAnswers] = useState<Answer[]>([]), [answerTotal, setAnswerTotal] = useState(0), [page, setPage] = useState(1), [term, setTerm] = useState('');
  const [ranking, setRanking] = useState<Word[]>([]), [wordTotal, setWordTotal] = useState(0), [wordPage, setWordPage] = useState(1);
  const [stops, setStops] = useState(''), [phrases, setPhrases] = useState(''), [synonyms, setSynonyms] = useState('');
  const [title, setTitle] = useState(''), [hint, setHint] = useState('输入一个词或一句话');
  const dialog = useRef<HTMLDialogElement>(null), selected = useRef<number | null>(null), version = useRef<number | null>(null);
  selected.current = qid;
  const q = stats?.question || questions.find(item => item.id === qid);
  function fail(e: unknown) { setError(errorText(e)); if (e instanceof ApiError && e.status === 401) { setAuth('login'); setCsrf(''); } }
  async function list() { const rows = await api<Question[]>('/api/admin/questions'); setQuestions(rows); return rows; }
  async function session() { try { const data = await api('/api/admin/session'); setCsrf(data.csrf); setAuth('ready'); setError(''); } catch (e) { if (e instanceof ApiError && e.status === 401) setAuth('login'); else { setAuth('login'); fail(e); } } }
  useEffect(() => { session(); }, []);
  useEffect(() => { if (auth === 'ready') list().then(rows => setQid(rows.find(item => item.status === 'open')?.id ?? rows[0]?.id ?? null)).catch(fail); }, [auth]);
  async function refresh(force = false, id = qid) {
    if (!id) return;
    const result = await api(`/api/admin/questions/${id}/stats${!force && version.current !== null ? '?since=' + version.current : ''}`);
    if (selected.current !== id) return;
    if (!result.unchanged) { version.current = result.version; setStats(result); setQuestions(rows => rows.map(item => item.id === id ? result.question : item)); }
    else setStats(previous => previous ? { ...previous, job: result.job } : previous);
    setLastSync(new Date().toLocaleTimeString('zh-CN')); setError('');
  }
  useEffect(() => {
    version.current = null; setStats(null); setPage(1); setTerm(''); setWordPage(1); setAnswers([]); setRanking([]);
    let alive = true, timer: ReturnType<typeof setTimeout>, failures = 0;
    async function poll() {
      try { if (!document.hidden) { await refresh(false, qid); failures = 0; } } catch (e) { if (alive) fail(e); failures++; }
      if (alive) timer = setTimeout(poll, Math.min(30000, 5000 * (failures + 1)));
    }
    if (qid && auth === 'ready') poll();
    return () => { alive = false; clearTimeout(timer); };
  }, [qid, auth]);
  useEffect(() => { if (!stats) return; setStops(stats.rules.stopwords.join('\n')); setPhrases(stats.rules.phrases.join('\n')); setSynonyms(Object.entries(stats.rules.synonyms).map(([a, b]) => `${a}=${b}`).join('\n')); }, [qid, stats?.rule_version]);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === 'Escape') setFull(false); }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape); }, []);
  async function loadAnswers() { if (!qid) return; const id = qid; const data = await api(`/api/admin/questions/${id}/answers?page=${page}${term ? '&term=' + encodeURIComponent(term) : ''}`); if (selected.current === id) { setAnswers(data.items); setAnswerTotal(data.total); } }
  useEffect(() => { if (tab === 'answers' && auth === 'ready') { let active = true; const id = qid; if (id) api(`/api/admin/questions/${id}/answers?page=${page}${term ? '&term=' + encodeURIComponent(term) : ''}`).then(data => { if (active) { setAnswers(data.items); setAnswerTotal(data.total); } }).catch(e => { if (active) fail(e); }); return () => { active = false; }; } }, [qid, page, term, tab, stats?.version, auth]);
  useEffect(() => { if (!qid || auth !== 'ready') return; let active = true; api(`/api/admin/questions/${qid}/words?page=${wordPage}`).then(data => { if (active) { setRanking(data.items); setWordTotal(data.total); } }).catch(e => { if (active) fail(e); }); return () => { active = false; }; }, [qid, wordPage, stats?.version, auth]);
  async function action(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { fail(e); } finally { setBusy(false); } }
  function choose(word: string) { setFull(false); setTerm(word); setPage(1); setTab('answers'); }
  async function saveRules() {
    if (!q) return;
    const mapping: Record<string, string> = Object.create(null);
    for (const line of synonyms.split('\n').filter(x => x.trim())) { const pair = line.split('='); if (pair.length !== 2 || !pair.every(x => x.trim())) throw new Error('同义词请按每行 原词=归并词 填写'); mapping[pair[0].trim()] = pair[1].trim(); }
    const split = (value: string) => value.split(/[\n,，]/).map(x => x.trim()).filter(Boolean);
    await api(`/api/admin/questions/${q.id}/rules`, write('PUT', { version: q.version, stopwords: split(stops), phrases: split(phrases), synonyms: mapping }));
    await refresh(true); setNotice('重算已开始，完成后词云会自动更新。');
  }
  if (auth !== 'ready') return <main className="setup-shell"><section className="setup-card"><span className="brand-symbol">✧</span><h1>问卷云控制台</h1><p>登录后查看汇聚的想法，管理问题与回答。</p>{auth === 'loading' ? <p role="status">正在检查登录状态…</p> : <form onSubmit={e => { e.preventDefault(); action(async () => { const data = await api('/api/admin/login', write('POST', { username, password })); setCsrf(data.csrf); setPassword(''); setAuth('ready'); }); }}><label>管理员账号<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} required /></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="primary" disabled={busy}>{busy ? '正在登录…' : '进入控制台'}</button></form>}{error && <div role="alert" className="error-message">{error}</div>}<a className="inline-link" href="/">返回回答页 ↗</a></section></main>;
  return <main className="admin-shell"><header className="admin-header"><div className="admin-logo"><span className="brand-symbol">✧</span>问卷云<span>观测控制台</span></div><div className="actions"><a className="inline-link" href="/" target="_blank" rel="noreferrer">打开回答页 ↗</a><a className="secondary" href="/api/admin/share.svg" download="wenjuan-cloud-qr.svg">下载二维码</a><button className="secondary" onClick={() => dialog.current?.showModal()}>＋ 新建问题</button><button className="text-button" disabled={busy} onClick={() => action(async () => { await api('/api/admin/logout', write('POST', {})); setCsrf(''); setAuth('login'); setStats(null); })}>退出</button></div></header>
    <div className="admin-body"><div className="question-toolbar"><div><p className="section-overline">QUESTION OBSERVATORY</p><h1 className="question-heading">{q?.text || '创建你的第一个问题'}</h1></div><div className="actions">{q && <><span className={'collect-state ' + (q.status === 'paused' ? 'paused' : '')}>{q.status === 'open' ? '正在收集' : '已暂停'}</span><select aria-label="选择问题轮次" value={qid ?? ''} onChange={e => setQid(Number(e.target.value))}>{questions.map(item => <option value={item.id} key={item.id}>{item.text}</option>)}</select><button className="secondary" disabled={busy} onClick={() => action(async () => { await api(`/api/admin/questions/${q.id}`, write('PATCH', { status: q.status === 'open' ? 'paused' : 'open', version: q.version })); await list(); await refresh(true); })}>{q.status === 'open' ? 'Ⅱ 暂停' : '▷ 开启'}</button></>}</div></div>
      {error && <div className="error-message" role="alert">{error}<button className="text-button" onClick={() => action(async () => { await list(); await refresh(true); })}>刷新数据</button></div>}{notice && <div className="notice" role="status">{notice}</div>}{stats?.job.status === 'building' && <div className="notice" role="status">规则重算中，当前仍展示完整的上一版结果…</div>}{stats?.job.status === 'failed' && <div className="error-message" role="alert">上次规则重算未完成，旧统计仍有效。请在分词规则中重新保存。</div>}
      <div className="stats-grid"><div className="stat"><label>有效回答</label><strong>{stats?.valid_count ?? '—'}<small>条</small></strong></div><div className="stat"><label>汇聚词语</label><strong>{stats?.word_count ?? '—'}<small>个</small></strong></div><div className="stat"><label>已排除回答</label><strong>{stats ? stats.total_count - stats.valid_count : '—'}<small>条</small></strong></div></div>
      <nav className="tab-nav" aria-label="控制台视图">{[['cloud', '词云观测'], ['answers', '原始回答'], ['rules', '分词规则']].map(([id, label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>
      {tab === 'cloud' && <div className="cloud-layout"><section className={full ? 'screen-cloud' : 'panel'}><div className="panel-heading"><h2>{full ? q?.text : '想法星云'}</h2><div className="actions"><p>前 80 个词</p><button className="text-button" disabled={busy} onClick={() => action(() => refresh(true))}>刷新</button><button className="text-button" onClick={() => setFull(!full)}>{full ? '退出放大 ✕' : '放大 ⛶'}</button></div></div><WordCloud words={stats?.words || []} onSelect={choose} /><div className="table-foot"><span>点击词语，追溯原始回答</span><span>{lastSync ? '更新于 ' + lastSync : '等待数据'}</span></div></section><section className="panel"><div className="panel-heading"><h2>词语排名</h2><p>提及回答数</p></div><div className="ranking">{ranking.length ? ranking.map((w, i) => <div className="rank" key={w.term}><span className="rank-index">{String((wordPage - 1) * 30 + i + 1).padStart(2, '0')}</span><div><button onClick={() => choose(w.term)}>{w.term}</button><div className="rank-bar" style={{ width: `${100 * w.count / (stats?.words[0]?.count || 1)}%` }} /></div><strong>{w.count}</strong></div>) : <div className="empty-content">暂无词语</div>}</div><div className="table-foot"><span>共 {wordTotal} 词</span><div className="actions"><button className="text-button" aria-label="上一页词语" disabled={wordPage <= 1} onClick={() => setWordPage(wordPage - 1)}>‹</button><span>{wordPage}</span><button className="text-button" aria-label="下一页词语" disabled={wordPage * 30 >= wordTotal} onClick={() => setWordPage(wordPage + 1)}>›</button></div></div></section></div>}
      {tab === 'answers' && <section className="panel"><div className="panel-heading"><h2>{term ? `提及「${term}」的有效回答` : '全部原始回答'}</h2>{term && <button className="text-button" onClick={() => { setTerm(''); setPage(1); }}>清除筛选 ✕</button>}</div><div className="table-scroll"><table><thead><tr><th>回答内容</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{answers.map(item => <tr key={item.id} className={item.status === 'excluded' ? 'excluded' : ''}><td className="answer-row-text">{item.raw_text}</td><td className="nowrap">{time(item.created_at)}</td><td className="nowrap">{item.status === 'excluded' ? '已排除' : '有效'}</td><td><button className="text-button" disabled={busy || !stats} onClick={() => action(async () => { await api(`/api/admin/answers/${item.id}`, write('PATCH', { status: item.status === 'valid' ? 'excluded' : 'valid', version: stats?.version })); await refresh(true); await loadAnswers(); })}>{item.status === 'valid' ? '排除' : '恢复'}</button></td></tr>)}</tbody></table></div>{!answers.length && <div className="empty-content">暂无回答</div>}<div className="table-foot"><span>共 {answerTotal} 条 · 第 {page} 页</span><div className="actions"><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><button className="secondary" disabled={page * 20 >= answerTotal} onClick={() => setPage(page + 1)}>下一页</button></div></div></section>}
      {tab === 'rules' && <section className="panel"><div className="panel-heading"><h2>让词云更准确</h2><p>规则版本 {stats?.rule_version || 1}</p></div><form className="rules-form" onSubmit={e => { e.preventDefault(); action(saveRules); }}><p>保存后会从本轮所有原始回答重新计算，原文始终保留。新统计准备完成后整体替换；重复词按单条回答只计一次。</p><label>停用词<textarea rows={5} value={stops} onChange={e => setStops(e.target.value)} placeholder="每行一个不参与统计的词" /></label><label>保留短语<textarea rows={4} value={phrases} onChange={e => setPhrases(e.target.value)} placeholder={'每行一个完整短语，例如：\n人工智能\n工作生活平衡'} /></label><label>同义词合并<textarea rows={4} value={synonyms} onChange={e => setSynonyms(e.target.value)} placeholder={'每行一组：原词=归并词\nAI=人工智能'} /></label><button className="primary fit" disabled={busy || !stats || stats.job.status === 'building'}>{stats?.job.status === 'building' ? '正在重新统计…' : '保存规则并重新统计'}</button></form></section>}
      <footer className="admin-footer">按提及该词的有效回答条数计数；同条回答重复写同一个词只计一次。<br />最近回答：{time(stats?.latest_at || null)} · 页面可见时每 5 秒检查更新</footer></div>
    <dialog ref={dialog} className="question-dialog" aria-labelledby="new-question-title"><form className="question-form" onSubmit={e => { e.preventDefault(); action(async () => { const result = await api<Question>('/api/admin/questions', write('POST', { text: title, hint })); await list(); setQid(result.id); dialog.current?.close(); setTitle(''); setNotice('问题已创建，点击“开启”后即可收集回答。'); }); }}><div className="panel-heading"><h2 id="new-question-title">开启一个新的问题</h2><button className="text-button" type="button" onClick={() => dialog.current?.close()}>关闭 ✕</button></div><p>新轮次单独保存回答，创建后默认暂停。</p><label>问题内容<textarea autoFocus rows={3} maxLength={200} value={title} onChange={e => setTitle(e.target.value)} required /></label><label>回答提示<input maxLength={200} value={hint} onChange={e => setHint(e.target.value)} /></label>{error && <p role="alert" className="error-message">{error}</p>}<button type="submit" className="primary" disabled={busy || !title.trim()}>创建问题</button></form></dialog>
  </main>;
}
